import React, {useState} from 'react'
import {Button, Card, Divider, Drawer, List} from "antd";

export default function ProjectIssues() {
    const [open, setOpen] = useState(false)

    const raw = JSON.parse("{\"Locations\":[\"PAPs to be implemented abroad should not have regions\\/provinces for location.\"],\"Date of Approval\":[\"Date of approval is required if the PAP has at least been submitted to the NEDA.\"],\"Funding Sources (Infra)\":[\"The selected funding sources are not the same as those selected in infrastructure breakdown.\"],\"Total Cost vs Breakdown per Region\":[\"Total cost is not equal to breakdown per region.\"],\"Funding Sources (Total)\":[\"The selected funding sources are not the same as those selected in investment breakdown.\"],\"Total Cost vs Breakdown per Funding Source\":[\"Total cost must equal breakdown per funding source.\"]}")

    const issues = Object.keys(raw)
        .map((key) => ({
            label: key,
            content: Array.isArray(raw[key])
                ? raw[key].join(', ')
                : 'Invalid data',
        }))
        .map((issue, index) => ({
            key: index,
            label: issue.label,
            content: issue.content,
        }))

    return (
        <Card style={{
            marginBottom: 16
        }}>
            <Button type='primary' onClick={() => setOpen(true)}>Click Me!</Button>

            <Drawer open={open} title='Issues' closable onClose={() => setOpen(false)}>
                <List
                    key={record => record.key}
                    dataSource={issues}
                    pagination={false}
                    renderItem={(item) => <List.Item>
                        <List.Item.Meta title={item.label} />
                        {item.content}
                    </List.Item>}
                />
            </Drawer>

            <Card.Meta
                title={<Divider orientation='left'>Issues</Divider>}
                description='Click on the button to view a sample of issues generated by the System.'
            />
        </Card>
    )
}